/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.ListsAndUpdates;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdateEmployeeInfo extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEmployeeInfo
     */
    public UpdateEmployeeInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_designation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 60, 23, 22);

        txt_id.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_id);
        txt_id.setBounds(260, 60, 190, 28);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 120, 53, 22);

        txt_name.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(260, 110, 190, 28);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 170, 79, 22);

        txt_address.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_address);
        txt_address.setBounds(260, 170, 190, 28);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALARY:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 230, 67, 22);

        txt_salary.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_salary);
        txt_salary.setBounds(260, 230, 190, 28);

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESIGNATION:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 290, 117, 22);

        txt_designation.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_designation);
        txt_designation.setBounds(260, 290, 190, 28);

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PHONE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 360, 61, 22);

        txt_phone.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_phone);
        txt_phone.setBounds(260, 350, 190, 28);

        btn_back.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(90, 410, 75, 31);

        btn_update.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(310, 410, 99, 31);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 850, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        UpdateEmployeeInfo window;
        window = new UpdateEmployeeInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;user=sa;password=12345;" +
            "databaseName=BloodBank;");
            
            Statement statement = connection.createStatement();  
            String ID = txt_id.getText().toString();
             String NAME = txt_name.getText().toString();
              String ADDRESS = txt_address.getText().toString();
               String SALARY = txt_salary.getText().toString();
                String DESIGNATION = txt_designation.getText().toString();
                 String PHONE = txt_phone.getText().toString();
            int id = Integer.parseInt(ID);
            int phone = Integer.parseInt(PHONE);
            int salary = Integer.parseInt(SALARY);
            
            //String query= "update donor set DonorName='"+txt_name.getText().toString()+"',DonorArea='"+txt_area.getText().toString()+"', DonorAddress='"+txt_address.getText().toString()+"', DonorGender= '"+txt_gender.getText().toString()+"' ,DonorBloodGroup='"+txt_blood.getText().toString()+"',DonorPhoneNumber="+PhoneNum+" where DonorID="+iDnumber;
           // String query1="update donor set DonorName='"+txt_name.getText().toString()+"',DonorArea='"+txt_area.getText().toString()+"', DonorAddress='"+txt_address.getText().toString()+"', DonorGender= '"+txt_gender.getText().toString()+"' ,DonorBloodGroup='"+txt_blood.getText().toString()+"',DonorPhoneNumber='"+phoneNumber+"' where DonorID='"+ID+"';";
             String query2="update Employee set EmployeeName='"+NAME+"',EmployeeAddress='"+ADDRESS+"', EmployeeSalary='"+salary+"', EmployeeDesignation= '"+DESIGNATION+"' ,EmployeePhoneNumber='"+phone+"' where EmployeeID='"+id+"';";
            statement.execute(query2);
              JOptionPane.showMessageDialog(null, "Update Successful!");
              
              employeeList window;
              window = new employeeList();
             window.setVisible(true);
             this.setVisible(false);
              
        }catch (Exception e) {  
             e.printStackTrace();
             JOptionPane.showMessageDialog(null, "exception");
         }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployeeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_address;
    public javax.swing.JTextField txt_designation;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_name;
    public javax.swing.JTextField txt_phone;
    public javax.swing.JTextField txt_salary;
    // End of variables declaration//GEN-END:variables
}
