/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.ListsAndUpdates;

import JForms.Pages.donorPage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdateBloodInventory extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDonorInfo
     */
    public UpdateBloodInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_BagNumber = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        txt_RBC = new javax.swing.JTextField();
        txt_WBC = new javax.swing.JTextField();
        txt_Platelets = new javax.swing.JTextField();
        txt_Plasma = new javax.swing.JTextField();
        txt_Heamoglobin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_DonorID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BagNumber:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 70, 166, 22);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity Available:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 120, 182, 22);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Red Blood Cells:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 170, 166, 22);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("White Blood Cells:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 220, 166, 22);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Platelets:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 166, 22);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plasma:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 320, 166, 22);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Heamoglobin:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 360, 166, 22);

        txt_BagNumber.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txt_BagNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BagNumberActionPerformed(evt);
            }
        });
        jPanel1.add(txt_BagNumber);
        txt_BagNumber.setBounds(328, 73, 148, 28);

        txt_quantity.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_quantity);
        txt_quantity.setBounds(328, 119, 148, 28);

        txt_RBC.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_RBC);
        txt_RBC.setBounds(328, 158, 148, 28);

        txt_WBC.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txt_WBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WBCActionPerformed(evt);
            }
        });
        jPanel1.add(txt_WBC);
        txt_WBC.setBounds(328, 210, 148, 28);

        txt_Platelets.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_Platelets);
        txt_Platelets.setBounds(328, 256, 148, 28);

        txt_Plasma.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_Plasma);
        txt_Plasma.setBounds(328, 302, 148, 28);

        txt_Heamoglobin.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(txt_Heamoglobin);
        txt_Heamoglobin.setBounds(328, 348, 148, 28);

        jButton1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 410, 93, 31);

        btn_update.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(328, 406, 148, 31);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Donor ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 30, 166, 22);

        txt_DonorID.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txt_DonorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DonorIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_DonorID);
        txt_DonorID.setBounds(328, 27, 148, 28);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 540, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try{
            
            
            
            
            /*DonorID int foreign key references donor(DonorID),
                BagNumber int identity(4000,1)not null primary key,
                QuantityAvailable int,
                 RedBloodCells varchar(100),
                  WhiteBloodCells varchar(100),
              Platelets varchar(100),
                  Plasma varchar(100),
                          Heamoglobin varchar(100)*/
            
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection( "jdbc:sqlserver://localhost:1433;user=sa;password=12345;" +
            "databaseName=BloodBank;");
            
            Statement statement = connection.createStatement();  
            String ID = txt_BagNumber.getText().toString();
            int iDnumber = Integer.parseInt(ID);
            
            //String Heamoglobin = txt_Heamoglobin.getText().toString();
           // int PhoneNum = Integer.parseInt(Heamoglobin);
            //String query= "update donor set DonorName='"+txt_name.getText().toString()+"',DonorArea='"+txt_area.getText().toString()+"', DonorAddress='"+txt_address.getText().toString()+"', DonorGender= '"+txt_gender.getText().toString()+"' ,DonorBloodGroup='"+txt_blood.getText().toString()+"',DonorPhoneNumber="+PhoneNum+" where DonorID="+iDnumber;
            String query1="update BloodInventory set QuantityAvailable='"+txt_quantity.getText().toString()+"',RedBloodCells='"+txt_RBC.getText().toString()+"', WhiteBloodCells='"+txt_WBC.getText().toString()+"', Platelets= '"+txt_Platelets.getText().toString()+"' ,Plasma='"+txt_Plasma.getText().toString()+"',Heamoglobin='"+txt_Heamoglobin.getText().toString()+"' where BagNumber="+iDnumber+";";
            statement.execute(query1);
              JOptionPane.showMessageDialog(null, "Update Successful!");
              
              BloodInventoryList window;
              window = new BloodInventoryList();
             window.setVisible(true);
             this.setVisible(false);
              
        }catch (Exception e) {  
             e.printStackTrace();
             JOptionPane.showMessageDialog(null, "exception");
         }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BloodInventoryList window;
        window = new BloodInventoryList();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_BagNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BagNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BagNumberActionPerformed

    private void txt_WBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WBCActionPerformed

    private void txt_DonorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DonorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonorIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBloodInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBloodInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBloodInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBloodInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBloodInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_BagNumber;
    public javax.swing.JTextField txt_DonorID;
    public javax.swing.JTextField txt_Heamoglobin;
    public javax.swing.JTextField txt_Plasma;
    public javax.swing.JTextField txt_Platelets;
    public javax.swing.JTextField txt_RBC;
    public javax.swing.JTextField txt_WBC;
    public javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
