package JForms.Pages;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class derbInfo extends javax.swing.JFrame {

    /**
     * Creates new form derbInfo
     */
    public derbInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_DONOR = new javax.swing.JButton();
        btn_EMPLOYEE = new javax.swing.JButton();
        btn_RECIPIENTS = new javax.swing.JButton();
        btn_donation = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        btn_DONOR.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_DONOR.setText("DONOR");
        btn_DONOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DONORActionPerformed(evt);
            }
        });
        jPanel1.add(btn_DONOR);
        btn_DONOR.setBounds(350, 210, 165, 31);

        btn_EMPLOYEE.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_EMPLOYEE.setText("EMPLOYEE");
        btn_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EMPLOYEEActionPerformed(evt);
            }
        });
        jPanel1.add(btn_EMPLOYEE);
        btn_EMPLOYEE.setBounds(350, 280, 165, 31);

        btn_RECIPIENTS.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_RECIPIENTS.setText("RECIPIENTS");
        btn_RECIPIENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RECIPIENTSActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RECIPIENTS);
        btn_RECIPIENTS.setBounds(350, 350, 165, 31);

        btn_donation.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_donation.setText("DONATION INFO");
        btn_donation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donationActionPerformed(evt);
            }
        });
        jPanel1.add(btn_donation);
        btn_donation.setBounds(350, 420, 165, 31);

        jButton2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jButton2.setText("BLOOD INFO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 490, 165, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/intro.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DONORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DONORActionPerformed
        donorPage window;
        window = new donorPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_DONORActionPerformed

    private void btn_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EMPLOYEEActionPerformed
        employeePage window;
        window = new employeePage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_EMPLOYEEActionPerformed

    private void btn_RECIPIENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RECIPIENTSActionPerformed
        recipientPage window;
        window = new recipientPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RECIPIENTSActionPerformed

    private void btn_donationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donationActionPerformed
        donationPage window;
        window = new donationPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_donationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bloodInfoPage window;
        window = new bloodInfoPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(derbInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(derbInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(derbInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(derbInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new derbInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DONOR;
    private javax.swing.JButton btn_EMPLOYEE;
    private javax.swing.JButton btn_RECIPIENTS;
    private javax.swing.JButton btn_donation;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
