package JForms.Pages;

import JForms.InsertInfo.insertRecipientInfo;
import JForms.ListsAndUpdates.recipientList;
import JForms.SearchPage.RecipientSearchPage;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class recipientPage extends javax.swing.JFrame {

    /**
     * Creates new form recipientPage
     */
    public recipientPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_NEWRECIPIENTS = new javax.swing.JButton();
        btn_RECIPIENTSLIST = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        btn_NEWRECIPIENTS.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_NEWRECIPIENTS.setText("NEW RECIPIENTS");
        btn_NEWRECIPIENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NEWRECIPIENTSActionPerformed(evt);
            }
        });
        jPanel1.add(btn_NEWRECIPIENTS);
        btn_NEWRECIPIENTS.setBounds(90, 90, 171, 31);

        btn_RECIPIENTSLIST.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_RECIPIENTSLIST.setText("RECIPIENTS LIST");
        btn_RECIPIENTSLIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RECIPIENTSLISTActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RECIPIENTSLIST);
        btn_RECIPIENTSLIST.setBounds(90, 180, 167, 31);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(35, 26, 65, 29);

        btn_Search.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_Search.setText("SEARCH");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Search);
        btn_Search.setBounds(90, 260, 171, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-5, -3, 330, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NEWRECIPIENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NEWRECIPIENTSActionPerformed
        insertRecipientInfo window;
        window = new insertRecipientInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_NEWRECIPIENTSActionPerformed

    private void btn_RECIPIENTSLISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RECIPIENTSLISTActionPerformed
        JTable jTable1 = null;
        recipientList window;
        window = new recipientList();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RECIPIENTSLISTActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        derbInfo window;
        window = new derbInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        RecipientSearchPage window;
        window = new RecipientSearchPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recipientPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NEWRECIPIENTS;
    private javax.swing.JButton btn_RECIPIENTSLIST;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
