package JForms.InsertInfo;

import DatabaseFiles.InsertRecipientInfoOperation;
import JForms.Pages.recipientPage;
import JForms.Pages.recipientPage;
import JavaFiles.DonorInfo;
import JavaFiles.RecipientInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class insertRecipientInfo extends javax.swing.JFrame {
     
    InsertRecipientInfoOperation ope = new  InsertRecipientInfoOperation();
    /**
     * Creates new form insertRecipientInfo
     */
    public insertRecipientInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_RName = new javax.swing.JTextField();
        cmbox_BLOODTYPE = new javax.swing.JComboBox<>();
        txt_AGE = new javax.swing.JTextField();
        cmbox_GENDER = new javax.swing.JComboBox<>();
        txt_RAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_RPHONE = new javax.swing.JTextField();
        btn_SUBMIT = new javax.swing.JButton();
        btn_CANCEL = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_RArea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_DonationNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(46, 119, 144, 22);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BLOOD TYPE :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(46, 164, 144, 28);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AGE : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(48, 220, 142, 22);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(46, 277, 142, 22);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADDRESS :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(46, 330, 142, 22);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHONE :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(46, 439, 142, 22);

        txt_RName.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_RName);
        txt_RName.setBounds(301, 118, 197, 28);

        cmbox_BLOODTYPE.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cmbox_BLOODTYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel1.add(cmbox_BLOODTYPE);
        cmbox_BLOODTYPE.setBounds(301, 166, 197, 28);

        txt_AGE.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_AGE);
        txt_AGE.setBounds(301, 219, 197, 28);

        cmbox_GENDER.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cmbox_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jPanel1.add(cmbox_GENDER);
        cmbox_GENDER.setBounds(301, 276, 197, 28);

        txt_RAddress.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_RAddress);
        txt_RAddress.setBounds(301, 329, 197, 28);

        jLabel8.setFont(new java.awt.Font("Cambria Math", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RECIPIENTS INFORMATION");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(102, 23, 362, 29);

        txt_RPHONE.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_RPHONE);
        txt_RPHONE.setBounds(301, 438, 197, 28);

        btn_SUBMIT.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_SUBMIT.setText("SUBMIT");
        btn_SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SUBMITActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SUBMIT);
        btn_SUBMIT.setBounds(301, 585, 120, 31);

        btn_CANCEL.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_CANCEL.setText("CANCEL");
        btn_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CANCELActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CANCEL);
        btn_CANCEL.setBounds(63, 585, 125, 31);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AREA:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(46, 384, 142, 22);

        txt_RArea.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_RArea);
        txt_RArea.setBounds(301, 383, 197, 28);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DONATION NO :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(46, 498, 157, 22);

        txt_DonationNo.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txt_DonationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DonationNoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_DonationNo);
        txt_DonationNo.setBounds(301, 497, 197, 28);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Insert.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1, 0, 600, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CANCELActionPerformed
        recipientPage window;
        window = new recipientPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CANCELActionPerformed

    private void btn_SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SUBMITActionPerformed
        // TODO add your handling code here:
        
        RecipientInfo aData=new RecipientInfo(txt_RName.getText(),txt_AGE.getText(),cmbox_GENDER.getSelectedItem().toString(), cmbox_BLOODTYPE.getSelectedItem().toString(),
                txt_RAddress.getText(),txt_RArea.getText(),txt_RPHONE.getText(),txt_DonationNo.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_btn_SUBMITActionPerformed

    private void txt_DonationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DonationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonationNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertRecipientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertRecipientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertRecipientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertRecipientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertRecipientInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CANCEL;
    private javax.swing.JButton btn_SUBMIT;
    private javax.swing.JComboBox<String> cmbox_BLOODTYPE;
    private javax.swing.JComboBox<String> cmbox_GENDER;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_AGE;
    private javax.swing.JTextField txt_DonationNo;
    private javax.swing.JTextField txt_RAddress;
    private javax.swing.JTextField txt_RArea;
    private javax.swing.JTextField txt_RName;
    private javax.swing.JTextField txt_RPHONE;
    // End of variables declaration//GEN-END:variables
}
