package JForms.InsertInfo;

import DatabaseFiles.InsertDonorInfoOperation;
import JForms.Pages.donorPage;
import JForms.Pages.donorPage;
import JavaFiles.DonorInfo;
import JavaFiles.Employee;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class insertDonorInfo extends javax.swing.JFrame {
    
     InsertDonorInfoOperation ope = new  InsertDonorInfoOperation();

    /**
     * Creates new form insertDonorInfo
     */
    public insertDonorInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Daddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_DArea = new javax.swing.JTextField();
        txt_Dname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbox_GENDER = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbox_BLOODGROUP = new javax.swing.JComboBox<>();
        txt_DPHONE = new javax.swing.JTextField();
        txt_ELIGIBILITY = new javax.swing.JTextField();
        btn_SUBMIT = new javax.swing.JButton();
        btn_CANCEL = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        txt_Daddress.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_Daddress);
        txt_Daddress.setBounds(160, 270, 120, 28);

        jLabel9.setFont(new java.awt.Font("Cambria Math", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Donor Information");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 30, 325, 44);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADDRESS :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 113, 22);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AREA :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 210, 77, 22);

        txt_DArea.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_DArea);
        txt_DArea.setBounds(160, 200, 120, 28);

        txt_Dname.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_Dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Dname);
        txt_Dname.setBounds(160, 140, 120, 28);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 130, 92, 22);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ELIGIBILITY :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 270, 126, 22);

        cmbox_GENDER.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cmbox_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbox_GENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbox_GENDERActionPerformed(evt);
            }
        });
        jPanel1.add(cmbox_GENDER);
        cmbox_GENDER.setBounds(530, 130, 120, 28);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BLOOD GROUP :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 170, 150, 22);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHONE :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 210, 79, 22);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 77, 22);

        cmbox_BLOODGROUP.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cmbox_BLOODGROUP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel1.add(cmbox_BLOODGROUP);
        cmbox_BLOODGROUP.setBounds(530, 170, 120, 28);

        txt_DPHONE.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jPanel1.add(txt_DPHONE);
        txt_DPHONE.setBounds(530, 220, 120, 23);

        txt_ELIGIBILITY.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_ELIGIBILITY);
        txt_ELIGIBILITY.setBounds(530, 270, 120, 28);

        btn_SUBMIT.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_SUBMIT.setText("SUBMIT");
        btn_SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SUBMITActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SUBMIT);
        btn_SUBMIT.setBounds(510, 380, 97, 31);

        btn_CANCEL.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_CANCEL.setText("CANCEL");
        btn_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CANCELActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CANCEL);
        btn_CANCEL.setBounds(170, 380, 95, 31);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Insert.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1, 0, 730, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DnameActionPerformed

    private void cmbox_GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbox_GENDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbox_GENDERActionPerformed

    private void btn_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CANCELActionPerformed
         donorPage window;
        window = new donorPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CANCELActionPerformed

    private void btn_SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SUBMITActionPerformed
        // TODO add your handling code here:
    
        DonorInfo aData=new DonorInfo(txt_Dname.getText(),cmbox_GENDER.getSelectedItem().toString(), cmbox_BLOODGROUP.getSelectedItem().toString(),
                txt_Daddress.getText(),txt_DArea.getText(),txt_DPHONE.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_btn_SUBMITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertDonorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertDonorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertDonorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertDonorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertDonorInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CANCEL;
    private javax.swing.JButton btn_SUBMIT;
    private javax.swing.JComboBox<String> cmbox_BLOODGROUP;
    private javax.swing.JComboBox<String> cmbox_GENDER;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DArea;
    private javax.swing.JTextField txt_DPHONE;
    private javax.swing.JTextField txt_Daddress;
    private javax.swing.JTextField txt_Dname;
    private javax.swing.JTextField txt_ELIGIBILITY;
    // End of variables declaration//GEN-END:variables
}
