/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.InsertInfo;

import DatabaseFiles.InsertDonationDetailsOperation;
import JForms.Pages.donationPage;
import JavaFiles.DonationDetails;
import JavaFiles.RecipientInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class InsertDonationDetails extends javax.swing.JFrame {
    
    InsertDonationDetailsOperation ope = new  InsertDonationDetailsOperation();
    /**
     * Creates new form InsertDonationDetails
     */
    public InsertDonationDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_BagNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Hospital = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_CollectionDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_DonationDate = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submitDetails = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donation Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(193, 39, 172, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BAG NO :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 120, 110, 22);

        txt_BagNo.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_BagNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BagNoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_BagNo);
        txt_BagNo.setBounds(372, 119, 143, 28);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOSPITAL :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 180, 130, 22);

        txt_Hospital.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_Hospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HospitalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Hospital);
        txt_Hospital.setBounds(372, 180, 143, 28);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE OF COLLECTION :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 240, 248, 22);

        txt_CollectionDate.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_CollectionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CollectionDateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_CollectionDate);
        txt_CollectionDate.setBounds(372, 242, 143, 28);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE OF DONATION :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 310, 211, 22);

        txt_DonationDate.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_DonationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DonationDateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_DonationDate);
        txt_DonationDate.setBounds(372, 305, 143, 28);

        txt_amount.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        jPanel1.add(txt_amount);
        txt_amount.setBounds(372, 377, 143, 28);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AMOUNT OF BLOOD GIVEN :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 380, 277, 22);

        submitDetails.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        submitDetails.setText("Submit");
        submitDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(submitDetails);
        submitDetails.setBounds(372, 466, 143, 31);

        jButton2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 470, 120, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Insert.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1, 0, 580, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed

    private void txt_DonationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DonationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonationDateActionPerformed

    private void txt_CollectionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CollectionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CollectionDateActionPerformed

    private void txt_HospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HospitalActionPerformed

    private void txt_BagNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BagNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BagNoActionPerformed

    private void submitDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDetailsActionPerformed
        // TODO add your handling code here:
        
        DonationDetails aData=new DonationDetails(txt_BagNo.getText(),txt_Hospital.getText(),
                txt_CollectionDate.getText(),txt_DonationDate.getText(),txt_amount.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_submitDetailsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        donationPage window;
        window = new donationPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertDonationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertDonationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertDonationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertDonationDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDonationDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitDetails;
    private javax.swing.JTextField txt_BagNo;
    private javax.swing.JTextField txt_CollectionDate;
    private javax.swing.JTextField txt_DonationDate;
    private javax.swing.JTextField txt_Hospital;
    private javax.swing.JTextField txt_amount;
    // End of variables declaration//GEN-END:variables
}
