/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.InsertInfo;

import DatabaseFiles.InsertEmployeeInfoOperation;
import JForms.Pages.employeePage;
import JavaFiles.Employee;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class InsertEmployeeInfo extends javax.swing.JFrame {

    InsertEmployeeInfoOperation ope = new  InsertEmployeeInfoOperation();
    
    public InsertEmployeeInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_address = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        txt_address.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        jPanel1.add(txt_address);
        txt_address.setBounds(282, 215, 211, 28);

        txt_name.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(282, 139, 211, 28);

        txt_salary.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_salary);
        txt_salary.setBounds(282, 286, 211, 28);

        txt_designation.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_designation);
        txt_designation.setBounds(282, 356, 211, 28);

        txt_phone.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_phone);
        txt_phone.setBounds(282, 427, 211, 28);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADDRESS :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(79, 218, 101, 22);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALARY :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(79, 289, 101, 22);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESIGNATION :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(79, 362, 146, 22);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(79, 433, 121, 22);

        btn_submit.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(379, 522, 114, 31);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAME :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(79, 145, 146, 22);

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EMPLOYEE  INFORMATION");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(67, 49, 420, 29);

        btn_cancel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(79, 522, 108, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Insert.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1, 0, 580, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
       
        Employee aData=new Employee(txt_name.getText(),txt_address.getText(),txt_salary.getText(),txt_designation.getText(),txt_phone.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        
    }//GEN-LAST:event_txt_addressActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        employeePage window;
        window = new employeePage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertEmployeeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_salary;
    // End of variables declaration//GEN-END:variables
}
