package JForms.InsertInfo;

import DatabaseFiles.insertBloodInfoOperation;
import JForms.Pages.bloodInfoPage;
import JavaFiles.BloodInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class insertBloodInfo extends javax.swing.JFrame {
     
    insertBloodInfoOperation ope = new  insertBloodInfoOperation();
    /**
     * Creates new form insertBloodInfo
     */
    public insertBloodInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_QUANTITY = new javax.swing.JTextField();
        txt_PLASMA = new javax.swing.JTextField();
        txt_PLATELETS = new javax.swing.JTextField();
        txt_REDCELLS = new javax.swing.JTextField();
        txt_WHITECELLS = new javax.swing.JTextField();
        txt_HEAMOGLOBIN = new javax.swing.JTextField();
        btn_SUBMIT = new javax.swing.JButton();
        btn_CANCEL = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_DonorID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUANTITY :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(15, 142, 213, 22);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLASMA :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(15, 185, 213, 22);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLATELETS :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(15, 236, 213, 22);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RED BLOOD CELLS :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(15, 288, 213, 22);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WHITE BLOOD CELLS :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(15, 344, 213, 22);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HEAMOGLOBIN :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(15, 401, 213, 22);

        txt_QUANTITY.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_QUANTITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QUANTITYActionPerformed(evt);
            }
        });
        jPanel1.add(txt_QUANTITY);
        txt_QUANTITY.setBounds(234, 139, 155, 28);

        txt_PLASMA.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_PLASMA);
        txt_PLASMA.setBounds(234, 182, 155, 28);

        txt_PLATELETS.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_PLATELETS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PLATELETSActionPerformed(evt);
            }
        });
        jPanel1.add(txt_PLATELETS);
        txt_PLATELETS.setBounds(234, 233, 155, 28);

        txt_REDCELLS.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_REDCELLS);
        txt_REDCELLS.setBounds(234, 285, 155, 28);

        txt_WHITECELLS.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jPanel1.add(txt_WHITECELLS);
        txt_WHITECELLS.setBounds(234, 341, 155, 28);

        txt_HEAMOGLOBIN.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        txt_HEAMOGLOBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HEAMOGLOBINActionPerformed(evt);
            }
        });
        jPanel1.add(txt_HEAMOGLOBIN);
        txt_HEAMOGLOBIN.setBounds(234, 398, 155, 28);

        btn_SUBMIT.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_SUBMIT.setText("SUBMIT");
        btn_SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SUBMITMouseClicked(evt);
            }
        });
        btn_SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SUBMITActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SUBMIT);
        btn_SUBMIT.setBounds(234, 502, 97, 31);

        btn_CANCEL.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_CANCEL.setText("CANCEL");
        btn_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CANCELActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CANCEL);
        btn_CANCEL.setBounds(64, 502, 107, 31);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BLOOD INVENTORY");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(104, 20, 256, 30);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DONOR ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(15, 93, 114, 22);

        txt_DonorID.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(txt_DonorID);
        txt_DonorID.setBounds(234, 93, 155, 28);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Insert.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1, 0, 470, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_QUANTITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QUANTITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QUANTITYActionPerformed

    private void txt_PLATELETSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PLATELETSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PLATELETSActionPerformed

    private void txt_HEAMOGLOBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HEAMOGLOBINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HEAMOGLOBINActionPerformed

    private void btn_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CANCELActionPerformed
        bloodInfoPage window;
        window = new bloodInfoPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CANCELActionPerformed

    private void btn_SUBMITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SUBMITMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SUBMITMouseClicked

    private void btn_SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SUBMITActionPerformed
        // TODO add your handling code here:
        
        BloodInfo aData=new BloodInfo(txt_DonorID.getText(),txt_QUANTITY.getText(),txt_PLASMA.getText(),
                txt_PLATELETS.getText(),txt_REDCELLS.getText(),txt_WHITECELLS.getText(),txt_HEAMOGLOBIN.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_btn_SUBMITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertBloodInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertBloodInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertBloodInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertBloodInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertBloodInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CANCEL;
    private javax.swing.JButton btn_SUBMIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DonorID;
    private javax.swing.JTextField txt_HEAMOGLOBIN;
    private javax.swing.JTextField txt_PLASMA;
    private javax.swing.JTextField txt_PLATELETS;
    private javax.swing.JTextField txt_QUANTITY;
    private javax.swing.JTextField txt_REDCELLS;
    private javax.swing.JTextField txt_WHITECELLS;
    // End of variables declaration//GEN-END:variables
}
