/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.SearchPage;

import DatabaseFiles.DBConnect;
import JForms.ListsAndUpdates.donorList;
import JForms.Pages.donorPage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DonorSearchPage extends javax.swing.JFrame {

    /**
     * Creates new form DonorSearchPage
     */
    public DonorSearchPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectOne = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_name_search = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        AreaRadio = new javax.swing.JRadioButton();
        BloodGroupRadio = new javax.swing.JRadioButton();
        EligibilityRadio = new javax.swing.JRadioButton();
        NameRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH PAGE FOR DONOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(38, 42, 328, 29);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search By ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(38, 124, 144, 26);

        txt_name.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name);
        txt_name.setBounds(38, 412, 176, 28);

        btn_name_search.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        btn_name_search.setText("Search");
        btn_name_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_name_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_name_search);
        btn_name_search.setBounds(275, 411, 91, 31);

        btn_back.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(146, 495, 104, 31);

        AreaRadio.setBackground(new java.awt.Color(102, 0, 0));
        selectOne.add(AreaRadio);
        AreaRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AreaRadio.setForeground(new java.awt.Color(255, 255, 255));
        AreaRadio.setText("Area");
        AreaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaRadioActionPerformed(evt);
            }
        });
        jPanel1.add(AreaRadio);
        AreaRadio.setBounds(38, 217, 67, 31);

        BloodGroupRadio.setBackground(new java.awt.Color(102, 0, 0));
        selectOne.add(BloodGroupRadio);
        BloodGroupRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BloodGroupRadio.setForeground(new java.awt.Color(255, 255, 255));
        BloodGroupRadio.setText("Blood Group");
        BloodGroupRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupRadioActionPerformed(evt);
            }
        });
        jPanel1.add(BloodGroupRadio);
        BloodGroupRadio.setBounds(38, 266, 131, 31);

        EligibilityRadio.setBackground(new java.awt.Color(102, 0, 0));
        selectOne.add(EligibilityRadio);
        EligibilityRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EligibilityRadio.setForeground(new java.awt.Color(255, 255, 255));
        EligibilityRadio.setText("Eligibility");
        EligibilityRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EligibilityRadioActionPerformed(evt);
            }
        });
        jPanel1.add(EligibilityRadio);
        EligibilityRadio.setBounds(38, 315, 101, 31);

        NameRadio.setBackground(new java.awt.Color(102, 0, 0));
        selectOne.add(NameRadio);
        NameRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameRadio.setForeground(new java.awt.Color(255, 255, 255));
        NameRadio.setText("Name");
        NameRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameRadioActionPerformed(evt);
            }
        });
        jPanel1.add(NameRadio);
        NameRadio.setBounds(38, 168, 77, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1, 0, 440, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_name_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_name_searchActionPerformed
        
         String value = txt_name.getText();
        
         String radioText = "";
         
        DBConnect ne = new DBConnect();
        Connection con=null; Statement st = null;
        try{
            con = ne.connectToDB();
        }catch(Exception e)
        {
            System.out.println("Database Not Connected") ;
        }
        try{
            st = con.createStatement();

        }catch(Exception e){
            System.out.println("Statement Creation Problem");
        }
        try{
            
            String query = null;
            
                if(NameRadio.isSelected())
            {
                radioText=NameRadio.getText();
                System.out.println(radioText);
                query = "SELECT  * from donor where  DonorName = '"+value+"'";
            }
            else if(AreaRadio.isSelected())
             {
                 radioText=AreaRadio.getText();
                 query = "SELECT  * from donor where  DonorArea = '"+value+"'";
            }
            else if(BloodGroupRadio.isSelected())
             {
                 radioText=BloodGroupRadio.getText();
                 query = "SELECT  * from donor where  DonorBloodGroup = '"+value+"'";
             }
            else if(EligibilityRadio.isSelected())
            {
                 radioText=EligibilityRadio.getText();
                 query = "SELECT  * from donor where  Eligibility = '"+value+"'";
            }

            //String query = "SELECT  * from donor where DonorBloodGroup = '"+value+"'"+"or DonorName = '"+value+"'"+"or DonorArea = '"+value+"'"
                                                    //+"or Eligibility = '"+value+"'";
            ResultSet rs = st.executeQuery(query);
            System.out.println(NameRadio);
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                donorList window;
                //ShowSearchResultByName window;
                //window = new ShowSearchResultByName(Name);
                window = new donorList(value);
                window.setVisible(true);
                this.setVisible(false);

            }else{
                JOptionPane.showMessageDialog(null, "Not Found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Not Found");
        }
    }//GEN-LAST:event_btn_name_searchActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        donorPage window;
        window = new donorPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void EligibilityRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EligibilityRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EligibilityRadioActionPerformed

    private void BloodGroupRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodGroupRadioActionPerformed

    private void AreaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaRadioActionPerformed

    private void NameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameRadioActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorSearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AreaRadio;
    private javax.swing.JRadioButton BloodGroupRadio;
    private javax.swing.JRadioButton EligibilityRadio;
    private javax.swing.JRadioButton NameRadio;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_name_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup selectOne;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
