/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.SearchPage;

import DatabaseFiles.DBConnect;
import JForms.ListsAndUpdates.employeeList;
import JForms.Pages.employeePage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author user
 */
public class EmployeeSearchPage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSearchPage
     */
    public EmployeeSearchPage() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_name_search = new javax.swing.JButton();
        btn_area_search = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_area = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH PAGE FOR EMPLOYEE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(28, 38, 352, 29);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search By ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(126, 137, 144, 29);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 68, 22);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 310, 67, 22);

        btn_name_search.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        btn_name_search.setText("Search");
        btn_name_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_name_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_name_search);
        btn_name_search.setBounds(330, 213, 91, 31);

        btn_area_search.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        btn_area_search.setText("Search");
        btn_area_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_area_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_area_search);
        btn_area_search.setBounds(330, 304, 91, 31);

        txt_name.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(152, 214, 104, 28);

        txt_area.setFont(new java.awt.Font("Cambria Math", 2, 18)); // NOI18N
        jPanel1.add(txt_area);
        txt_area.setBounds(152, 305, 104, 28);

        btn_back.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(152, 378, 104, 31);

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(152, 264, 95, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1, 0, 460, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        employeePage window;
        window = new employeePage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_name_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_name_searchActionPerformed
        String Name = txt_name.getText();
          
        
        DBConnect ne = new DBConnect();
        Connection con=null; Statement st = null;
        try{
             con = ne.connectToDB();
        }catch(Exception e)
        {
           System.out.println("Database Not Connected") ;
        }
        try{
            st = con.createStatement();
            
        }catch(Exception e){
            System.out.println("Statement Creation Problem");
        }
        try{
           
            String query = "SELECT  EmployeeID , EmployeeName ,EmployeeAddress ,EmployeeSalary ,EmployeeDesignation ,EmployeePhoneNumber from Employee where EmployeeName = '"+Name+"'" ;
            ResultSet rs = st.executeQuery(query);
            System.out.println(Name);
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                employeeList window;
                //ShowSearchResultByName window;
                //window = new ShowSearchResultByName(Name);
                window = new employeeList(Name);
                window.setVisible(true);
                this.setVisible(false);  
                
            }else{
                JOptionPane.showMessageDialog(null, "Name Not Found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Name Not Found");
        }
    }//GEN-LAST:event_btn_name_searchActionPerformed

    private void btn_area_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_area_searchActionPerformed
         String Area = txt_area.getText();
          
        
        DBConnect ne = new DBConnect();
        Connection con=null; Statement st = null;
        try{
             con = ne.connectToDB();
        }catch(Exception e)
        {
           System.out.println("Database Not Connected") ;
        }
        try{
            st = con.createStatement();
            
        }catch(Exception e){
            System.out.println("Statement Creation Problem");
        }
        try{
           
            String query = "SELECT  EmployeeID , EmployeeName ,EmployeeAddress ,EmployeeSalary ,EmployeeDesignation ,EmployeePhoneNumber from Employee where EmployeeAddress = '"+Area+"'";
            ResultSet rs = st.executeQuery(query);
            System.out.println(Area);
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                employeeList window;
                //ShowSearchResultByArea window;
                window = new employeeList(Area);
                window.setVisible(true);
                this.setVisible(false);  
                
            }else{
                JOptionPane.showMessageDialog(null, " Not Found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " Not Found");
        }
    }//GEN-LAST:event_btn_area_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_area_search;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_name_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
